# _target_: models.sequence.SequenceModel
_name_: model
layer:
  _name_: rnn
  cell:
    _name_: exprnn # Can change to gru to allow for orthogonal + gating options, i.e. the GORU
    d_model: 256
    hidden_activation: modrelu
    orthogonal: True
    ortho_args:
      method: dtriv # 'cayley' | 'exprnn' | 'dtriv'
      init: cayley # 'henaff' | 'cayley'
  # output_mode: state
prenorm: False
transposed: False
n_layers: 1
d_model: 256
residual: R
pool:
  _name_: sample
  pool: 1
  expand: 1
norm: layer
  # scalar: True # only applicable if transposed=True
# dropout: 0.2
dropinp: 0.0
