# @package model
# Example of composing our RNN classes to build more advanced models,
# such as the Gated Orthogonal Recurrent Unit
# https://arxiv.org/abs/1706.02761
# _target_: models.model.SequenceModel
_name_: model
layer:
  _name_: rnn
  cell:
    _name_: gru
    d_model: 256
    hidden_activation: modrelu
    gate: G
    reset: G
    orthogonal: True
    ortho_args:
      method: dtriv # 'cayley' | 'exprnn' | 'dtriv'
      init: cayley # 'henaff' | 'cayley'
n_layers: 1
d_model: 256
prenorm: False
residual: N
pool: null
norm: none
dropout: 0.0
