# @package model
# Config for the HiPPO-LegT (Translated Legendre) cell
# _target_: models.model.SequenceModel
_name_: model
layer:
  _name_: rnn
  cell:
    _name_: legt
    d_model: 256
    memory_size: 1
    memory_order: -1
    dt: 0.01
    discretization: bilinear
  return_output: True
n_layers: 1
d_model: 256
prenorm: False
residual: N
pool: null
norm: none
dropout: 0.0
# decoder: state
