# @package model
# Config for the HiPPO-LegS (Scaled Legendre) cell with timestamped input
# _target_: models.model.SequenceModel
_name_: model
layer:
  _name_: rnn
  cell:
    _name_: tlsi
    d_model: 256 # hidden size
    memory_size: 1
    memory_order: -1
    discretization: bilinear
  return_output: True
n_layers: 1
d_model: 256
prenorm: False
residual: R
pool: null
norm: layer
dropout: 0.0
# decoder: state # To use the hidden state to decode, pass in decoder=state at top level. If single layer, pass model.layer.return_output=false to save memory
